version: '3.8'
services:
  train:
    build:
      context: colortypemodel
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/data/colortype_train.csv:/app/data.csv
      - ${PWD}/colortypemodel/model/:/app/model/
  build-pages:
    build:
      context: codegen
      dockerfile: Dockerfile
    cap_add:
      - 'SYS_ADMIN'
    volumes:
      - ${PWD}/public:/pages
